### ISSUE TITLE
Support for background color in boxes

### ISSUE THREAD

**Issue by manast** [vadimdemedes/ink#510] opened 2022-04-03 13:47 UTC
I have seen that there are old discussions about this functionality. 

The reason for creating this new issue is that I believe that this feature is really a must-have, especially when there are no workarounds that I know of (let me know if there are please).

So why is it a must-have? well, because it is crucial for making good UIs in terminals. One of the most important use cases is for creating *selections*, but also to divide the screen into different areas, implement top and bottom bars, etc.

I post some examples of known terminal apps that use these techniques with good effect:

![image](https://user-images.githubusercontent.com/95200/161430961-8ed1d1df-5230-4e89-add0-9653fa2aa46f.png)

![image](https://user-images.githubusercontent.com/95200/161430999-388b48dd-b3a7-4a37-92f3-37b98615bba0.png)

![image](https://user-images.githubusercontent.com/95200/161431014-8eaaf3e6-6e01-4c28-b7ac-444c0c4d10bf.png)

![image](https://user-images.githubusercontent.com/95200/161431061-56d33907-183e-4d1f-a1b2-b0fa13b9c6ed.png)

**Comment by vadimdemedes** [comment] 2023-03-17 23:03
Duplicate of #469.

**Closed by vadimdemedes** 2023-03-17 23:03 UTC
