### ISSUE TITLE
[Feature request] Cursor position

### ISSUE THREAD

**Issue by streamich** [vadimdemedes/ink#335] opened 2020-07-19 14:46 UTC
Add ability to specify cursor position for a `<Text>` node. This will allow creating rich text editors using `ink` and Slate.js.

```jsx
<Text cursor={3}>foo bar</Text>
```

Where `cursor={3}` means the cursor will be set on to third character in the text, in this case on the empty space between "foo" and "bar".

**Comment by vadimdemedes** [comment] 2020-07-20 18:10
I had to solve this problem in [ink-text-input](https://github.com/vadimdemedes/ink-text-input) by faking the cursor, because it was too complicated to manage the "real" cursor in the terminal and related ANSI escapes. I guess I could extract that from this package and merge into Ink, so that it's provided out-of-the-box.

**Comment by vadimdemedes** [comment] 2020-07-20 18:11
Closing as a duplicate of https://github.com/vadimdemedes/ink/issues/251.

**Closed by vadimdemedes** 2020-07-20 18:11 UTC
