### ISSUE TITLE
memory leak 😨 / how can I assist with v2?

### ISSUE THREAD

**Issue by rozzzly** [vadimdemedes/ink#100] opened 2018-10-19 23:37 UTC
Hey @vadimdemedes! I really like this project, and have already started to use the `@next` branch in a project of mine but have run into several issues. I would like to help with the v2 rewrite.

The major issue is a memory leak. You use yoga which (for node) is compiled from C++ into a native add on. As with anything native, memory management is a vital concern and it appears the current implementation does not properly account for that. For every new react/dom node, a new [yoga node is created](https://github.com/vadimdemedes/ink/blob/next/src/create-renderer.js#L7) but when the react/dom node is removed [here](https://github.com/vadimdemedes/ink/blob/next/src/create-reconciler.js#L50) and [here](https://github.com/vadimdemedes/ink/blob/next/src/create-reconciler.js#L76) nothing is done to free up the allocated object. I believe this particular fix would be as simple as calling `child.yogaNode.free()` after `parent.removeChild(child)`. 

However, every time you [render](https://github.com/vadimdemedes/ink/blob/next/src/create-renderer.js#L101) the tree, a new yoga node is created for _every item_ in the tree and any old yoga nodes are left out in limbo.

I've found several other smaller issues with the implementation and would like to PR them.
 
I just wanted to A) make sure you were aware of these issues B) get your blessing C) discuss how I could help with the rewrite in general. For example: I think the dependency on `logUpdate` should be dropped and a lower-level implementation written that updates just the rows (or even columns) affected by a rerender; right now, it's redrawing the entire screen, even the unchanged parts—this causes me flickers.

**Comment by vadimdemedes** [comment] 2018-10-20 21:37
Thanks, glad you like the project!

Regarding memory leak, yes I'm aware of this issue. There's a simpler way to free up all nodes - `yogaNode.freeRecursive()`. I didn't add it, because `<Box>` has this method https://github.com/vadimdemedes/ink/blob/v2.0.0-2/src/components/Box.js#L52, which returns actual width of component. It's useful for things like progress bar, where you need to calculate the percentage of component width. Not sure how to work around it yet, what do you think?

> logUpdate should be dropped and a lower-level implementation written that updates just the rows (or even columns) affected by a rerender
I've tried that actually, there's a module exactly for this - https://github.com/mafintosh/ansi-diff-stream. Unfortunately, while upgrading [emoj](https://github.com/sindresorhus/emoj) to Ink 2, I noticed that this module sometimes renders spaces incorrectly. If you know of an alternative, happy to try it too!

> C) discuss how I could help with the rewrite in general.
It's pretty much done except of these two problems. What I would appreciate a lot though, if you could try building various layouts and try to break it, so that it can be fixed before release :)

**Comment by vadimdemedes** [comment] 2018-10-22 03:47
Released `2.0.0-3` to fix memory leak, which saves the last node tree and frees it up on each consequent render. Can't link to a commit, because GitHub is now having data inconsistency issues (can't see it).

**Comment by rozzzly** [comment] 2018-10-23 21:58
okay quick update:

checkout
https://github.com/rozzzly/ink/commits/next

Fixed an issue with the reconciler would A) throw a fit about `resetTextContent() is not a function` or B) concat old text with new text

This is a quick sketch to illustrate what I was seeing, but I'm writing it on the fly so it's possible it won't reproduce as-is. Any given a component such as this:

```jsx
class SayHello extends React.Component {
	render() {
		const { name } = this.props;
		
		if (name) {
			return (
		    	<Color red>
					{ `Your name is ${name}` }
					<HappyBirthday />
				</Color>
			);
		} else {
			return (
				<Color blue>
					{ 'You have no name!' }
				</Color>
			);
    	}
	}
}
```

1. You render `<SayHello />`
2. reconciler gets `{ type: 'Color', props: { blue: true }, children: 'You have no name!' }`
3. dom node gets for our `SayHello` element gets a `span` wrapper appended
4. we re-render with `<SayHello name='rozzzly' />
5. reconciler gets `{ type: 'Color', props: { red: true }, children: ['Hello',  { type: 'HappyBirthday', props:{}, children: null}]}`
6. Some Wrapper instance gets created for `children[0]`
7. `children[0]` and `children[1]` get appended to their parent **behind that phantom span from the previous render**
8. user sees `You have no Name!Your name is rozzzzly.:cake:` when we wanted them to see `Your name is rozzzzly.:cake:`

Anyway I'm tired typing 😠 lol that's roughly how I understood it a nights ago.

Adding a `resetTextContent` that removed those phantom `<span>` nodes fixed this issue

**Comment by vadimdemedes** [comment] 2018-10-30 04:38
Interesting. Thanks for the detailed repro steps, will check it out.

**Comment by vadimdemedes** [comment] 2018-11-05 01:00
Fixed via https://github.com/vadimdemedes/ink/commit/399c7817de4ac58dcd4dae37e9643870a4d6b8d8, thanks!

**Comment by vadimdemedes** [comment] 2018-11-05 02:39
Regarding diffing on update, I've decided not to do it just yet, until I see actual use cases for it. So far I haven't been able to reproduce the flickering even with some really "stressful" benchmarks. Output flickers only when amount of rows is bigger than the height of the terminal. In that case though, `log-update` can't update rows that are out of terminal viewport, I don't think there's workaround for this, unfortunately.

**Comment by rozzzly** [comment] 2018-11-05 23:47
Here's where I get screen flickers:

  * Terminal dimensions are at 140x14
  * 1st row contains a spinner (custom implementation for ink2, but functionally identical to `ink-spinner`
  * other 13 rows _filled_ with static content

I doubt these are the minimum requirements to get flickering either. I suspect your "stressful" benchmarks don't write nearly as much to the stdout buffer as my use case is.

A test like:
```typescript
const test = ({ name }) => (
    <Box>
        Hello {name} <Spinner type='bar' interval={100} />
    </Box>
```
will write frequently, sure. But each time the following is written to the stdout buffer:
```
\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[GHello rozzzly [=   ]\n\n
```
```
\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[GHello rozzzly [==  ]\n\n
```
```
\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[GHello rozzzly [ == ]\n\n
```
```
\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[GHello rozzzly [  ==]\n\n
```
and so on

But that's not even a single full line of text! Imagine constantly pushing 10x-100x as many bytes and you'll see why I hit a bottleneck at anything > 7fps or so.

That being said, what I want to do (build a cli dashboard for webpack) is a little extreme for ink as it stands. There are a lot of changes I would like/need to make, so I've started from scratch. When I publish, I'll link back to `ink` with appropriate attribution.

best of luck!

**Comment by rozzzly** [comment] 2018-11-05 23:47
btw I noticed you haven't tagged that last commit as `v2.0.0-4` yet 😉

**Comment by vadimdemedes** [comment] 2018-11-06 04:49
Sure, good luck with your own version of Ink :) Thanks for your help!

**Closed by vadimdemedes** 2018-11-06 04:49 UTC
