### ISSUE TITLE
Multiple identical static outputs in a row don't get rendered

### ISSUE THREAD

**Issue by jamestalmage** [vadimdemedes/ink#132] opened 2019-02-27 05:19 UTC
I'm using `Static` to log previously entered commands.

```jsx
previousCommands.map(({cmd})=> (<Static>{cmd}</Static>));
```

However, if I enter the same command twice, it doesn't get re-rendered.

My guess is that it has to do with this logic [here](https://github.com/vadimdemedes/ink/blob/da5ff3df952c817a305f3fc1c33165d04dfa17c1/src/render.js#L56). 

Removing the last condition of that line causes the static item to be rendered 3 times. But it gets rendered three new times for each copy of the command. So it trades one problem for another.

**Comment by vadimdemedes** [comment] 2019-02-27 07:00
There can only be one `<Static>` element:

> In order for this mechanism to work properly, at most one `<Static>` component must be present in your node tree and components that were rendered must never update their output.

Also, make sure to assign unique `key`s to each child of `<Static>`:

```jsx
<Static>
	{previousCommands.map(command => (
		<Command key={command.id}/>
	)}
</Static>
```

**Comment by vadimdemedes** [comment] 2019-03-04 07:28
Closing for now, let me know if it didn't work and I'll reopen it again ;)

**Comment by nikersify** [comment] 2019-03-24 23:54
I'm having the same problem, here's a minimal reproduction:
```js
import * as React from 'react'
import {useState, useEffect} from 'react'
import {Static, Box, Color, render} from 'ink'

function App() {
	const [lines, setLines] = useState([])

	useEffect(() => {
		setInterval(() =>
			setLines(l => l.concat(Math.random() < 0.9 ? 'a' : 'b')),
		1000)
	}, [])

	return (
		<>
			<Static>
				{lines.map((l, i) => <Box key={i}>{l}</Box>)}
			</Static>
			<Color green>{lines.length}</Color>
		</>
	)
}

render(<App/>)
```

Output:
```
b
a
b
a
b
a
b
a
30
```

The output should obviously be way longer, looks like if one "static line" is the same as the one above it, it doesn't get rendered - even when it has a correct `key`.

**Comment by vadimdemedes** [comment] 2019-03-26 05:28
Will take a look, thanks!

**Comment by vadimdemedes** [comment] 2019-03-27 05:24
Fix (https://github.com/vadimdemedes/ink/commit/98b3c3e9c59b1759c784761835631866fbf36911) is in master, will close this issue once new release is out.

**Comment by nikersify** [comment] 2019-03-27 09:13
Thanks for the quick fix @vadimdemedes!

**Comment by vadimdemedes** [comment] 2019-03-31 04:50
New release is out - https://github.com/vadimdemedes/ink/releases/tag/v2.1.0 🎆

**Closed by vadimdemedes** 2019-03-31 04:50 UTC
Labels: bug
