### ISSUE TITLE
React devtools

### ISSUE THREAD

**Issue by duncanbeevers** [vadimdemedes/ink#151] opened 2019-03-11 23:33 UTC
Is there a way to point the standalone React devtools at an ink app?

I tried pulling in the standalone tools to connect to the devtools server running at 8097, but the standalone launcher still appears married to the browser.

```js
import { default as ReactDevtoolsCore } from 'react-devtools-core';
ReactDevtoolsCore.connectToDevTools();
```

```
ReferenceError: window is not defined
```

**Comment by vadimdemedes** [comment] 2019-03-13 03:38
I haven't looked into it, but I'm pretty sure it would be a challenging task to integrate Ink with devtools. I don't think I have enough time to work on something that big right now. Feel free to experiment with it and let me know how it goes!

**Comment by vadimdemedes** [comment] 2020-05-03 14:18
Closing as duplicate of https://github.com/vadimdemedes/ink/issues/279.

**Closed by vadimdemedes** 2020-05-03 14:18 UTC
