### ISSUE TITLE
Support for `useSyncExternalStore`

### ISSUE THREAD

**Issue by jimmed** [vadimdemedes/ink#523] opened 2022-06-12 16:12 UTC
Following [this discussion from the React WG](https://github.com/reactwg/react-18/discussions/86), it would be amazing to see support for the `useSyncExternalStore` hook within Ink since its addition to React 18.

Unfortunately, the `useSyncExternalStore` function that React exposes calls a method of the same name within the renderer's dispatcher -- for Ink (as of v3.2.0) this function does not exist.

Attempting to call the hook results in an error much like this:

```
  ERROR  dispatcher.useSyncExternalStore is not a function

 node_modules/react/cjs/react.development.js:1674:21

 1671: }
 1672: function useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot) {
 1673:   var dispatcher = resolveDispatcher();
 1674:   return dispatcher.useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
 1675: }
 1676:
 1677: // Helpers to patch console.logs to avoid logging during side-effect free

 - useSyncExternalStore (node_modules/react/cjs/react.development.js:1674:21)
... stack trace from my Ink app ...
 - renderWithHooks (node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:6412:18)
 - mountIndeterminateComponent (node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:9238:13)
 - beginWork (node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:10476:16)
 - Object.invokeGuardedCallbackProd (node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:12101:10)
 - invokeGuardedCallback (node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:12292:31)
 - beginWork$1 (node_modules/ink/node_modules/react-reconciler/cjs/react-reconciler.development.js:16531:7)
 ```

I'm planning to get involved and implement this myself, given the library author's (very understandable) situation due to war -- I'm a little unsure where to begin but I'm hopeful I can make some progress on this!

**Comment by vadimdemedes** [comment] 2022-07-24 18:55
Support for React 18 is planned for the next major release. Closing this issue as a duplicate of #526.

**Closed by vadimdemedes** 2022-07-24 18:55 UTC
