### ISSUE TITLE
Shifting flex edges

### ISSUE THREAD

**Issue by duncanbeevers** [vadimdemedes/ink#154] opened 2019-03-12 05:47 UTC
In this simple application I create a flex layout with two columns, both set to `flexGrow={1}`.

Despite there being ample room for all content within both containers, the column edge shifts.

![2019-03-11 at 10 39 PM](https://user-images.githubusercontent.com/7367/54177274-e31d5900-444e-11e9-96b5-8986d595bed0.gif)

```js
function App() {
  const [input, setInput] = useState('');
  const [list, setList] = useState([]);

  useEffect(() => {
    const interval = setInterval(() => {
      setInput(input + '_');
      setList(list.concat(input).slice(-5));
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, [input, list, setInput, setList]);

  return (
    <Box flexDirection="row">
      <Box flexGrow={1} flexDirection="column">
        <Box>Left</Box>
        <Box>{input}</Box>
      </Box>
      <Box flexGrow={1} flexDirection="column">
        <Box>Right</Box>
        {list.map((item, i) => (
          <Box key={i}>{item}</Box>
        ))}
      </Box>
    </Box>
  );
}
```

**Comment by vadimdemedes** [comment] 2019-03-13 04:27
Thanks for a detailed issue! I found the root cause of it - terminal width. This bug occurs only on odd terminal width, like 79 columns for example. If you resize the terminal to an even width like 80 columns, you should no longer see that issue.

Simple fix would be to ensure layout width in Ink is always an even number. However, I'm afraid people will get confused why Ink's output doesn't stretch to full width of the terminal. Need to think about it more, but if you have any ideas how to solve it, feel free to post them here!

**Comment by vadimdemedes** [comment] 2020-06-18 09:53
My take above is wrong. I was able to fix this by explicitly setting the width of both columns to `50%`. Marking this as something that will be fixed as part of Ink 3 release.

**Comment by vadimdemedes** [comment] 2020-07-27 17:49
Ink 3 is out with the fix for this issue included! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)

**Closed by vadimdemedes** 2020-07-27 17:49 UTC
Labels: bug, shipped in v3
