### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by AsutoraGG** [vadimdemedes/ink#615] opened 2023-07-29 16:20 UTC
how to remove this error?

```
import { render } from 'ink';
import { App } from './src/ink/app.js'

render(<App arrayData={WhatNew} />)
```
(i saw old issue but idk how to solve)

**Comment by sindresorhus** [comment] 2023-07-30 11:25
Duplicate of #365

**Closed by sindresorhus** 2023-07-30 11:25 UTC
