### ISSUE TITLE
Margin or padding inside Color doesn't use background color

### ISSUE THREAD

**Issue by icopp** [vadimdemedes/ink#175] opened 2019-03-23 06:20 UTC
A simple example:

```
<Color bgCyan black>
  <Box padding={1}>Text here</Box>
</Color>
```

Expected result: `Text here` at the center of a cyan box with 1 padding all around

Actual result: `Text here` with cyan background, but at the center of a 1 padding black box

**Comment by vadimdemedes** [comment] 2019-03-27 04:56
I would recommend using `<Color>` with text children only, not with nested `<Box>`es. Think of `<Color>` and `<Text>` like `<span>` in the browser, it's uncommon to see nested `<div>`s in a `<span>`.

**Comment by icopp** [comment] 2019-03-27 17:24
That makes sense, but also makes me think that there's missing functionality there on `Box`. Of course, that's probably more suited to wait until after borders go on so any color stuff can take advantage of the same boundary handling.

**Comment by vadimdemedes** [comment] 2019-03-28 02:14
Yeah, there was support for coloring boxes initially, but there were some edge cases which made me revert this functionality. I should've documented those or noted somewhere, but I didn't. I will try to add support again and see how it goes.

**Comment by danikaze** [comment] 2019-04-01 04:30
I was trying to use this exactly, and this is how I solved it...
```
  const text = props.children;
  const middle = Math.floor((props.width - text.length)/ 2) + text.length;

  return (
    <ColorPipe styles='white.bold.bgblue'>
      {text.padStart(middle, ' ').padEnd(props.width, ' ')}
    </ColorPipe>
  );
```

**Comment by vadimdemedes** [comment] 2019-05-23 04:36
`<ColorPipe>` is a 3rd-party component, it could implement coloring differently than Ink's built-in `<Color>`. I will check it out!

**Comment by LitoMore** [comment] 2019-05-30 10:08
@danikaze [ink-color-pipe](https://github.com/LitoMore/ink-color-pipe) was designed for users who want to do some mutation with their color schemes.

Like this tool:

<img width="50%" height="50%" src="https://raw.githubusercontent.com/LitoMore/twe/master/media/twe-colors.gif" alt="twe-colors" />

**Comment by vadimdemedes** [comment] 2020-05-23 11:32
So the issue is when you have a box with padding, like `<Box padding={1}>Text</Box>`, for `<Color>` component there's nothing to color on first and third lines, because those are just empty.

I'm going to leave this issue open for now, but I think when Ink is going to have support for borders, this will get solved as part of that work.

**Comment by vadimdemedes** [comment] 2023-04-01 11:15
Closing, since the original issue was for `Color` component, which was removed in Ink 3.

**Closed by vadimdemedes** 2023-04-01 11:15 UTC
Labels: bug
