### ISSUE TITLE
measureElement returning null

### ISSUE THREAD

**Issue by dustinlacewell** [vadimdemedes/ink#465] opened 2021-07-27 07:22 UTC
I am using measureElement as described, and I am getting `{width: null, height: null}`

Any ideas of what would cause this?

**Comment by vadimdemedes** [comment] 2023-03-17 20:32
Could be a duplicate of #557. This is being fixed in https://github.com/vadimdemedes/ink/pull/561.

**Closed by vadimdemedes** 2023-03-17 20:32 UTC
